nodeapp/urls.py
from django.conf.urls import url,include
from django.urls import path
from . import views

urlpatterns=[
    #path('',views.index,name="index"),
    url(r'^$',views.index,name="index"),
	#url(r'^home',views.index,name="index"),  #主页 
]
#当了没有登录的时候，进入的一个界面
urlpatterns+=[
    url(r'publichistory',views.publicHistory,name="publichistory"),
]
#管理人员界面
urlpatterns+=[
    path(r'management/',views.ManagementListView.as_view(),name="management_list"),#as_view()把类当作函数
    path(r'management/<int:pk>',views.ManagementDetailView.as_view(),name="management_detail"),  #详细界面
]

#
urlpatterns+=[
    path(r'simulationparament/',views.SimulationParamentListView.as_view(),name="simulationparament_list"),
    path(r'simulationparament/<int:pk>',views.SimulationParamentDetailView.as_view(),name="simulationparament_detail"),
]

#用户登录界面
urlpatterns+=[
    path(r'accounts/',include('django.contrib.auth.urls')),
]

#用户设置参数的位置
urlpatterns+=[
    path(r'simulationhistory/',views.simulationHistoryListView.as_view(),name="simulation_history"),
]

#在这里用户提交表单，运行仿真
urlpatterns+=[
    path(r'runningsimulation/',views.runningsimulation,name="runningsimulation"),
]

#删除一条仿真记录
urlpatterns+=[
    path(r'simulationhistory/<int:pk>',views.delete_store_info,name="delete"),
]

#实现下载功能
urlpatterns+=[
    path(r'simulationhistory/<int:pf>/download',views.downloadfile,name='download'),
]

#终端测
urlpatterns+=[   
    path(r'terminalssh/<int:nodeId>',views.terminalSSH,name="terminalSSH"),
    path(r'terminalSelector', views.selectNodeTerminal, name = "terminalSelector")
]

#节点环境参赛表
urlpatterns+=[
    path(r'nodeEnviro',views.nodeEnviro,name="nodeEnviro")
]
#硬件仿真
urlpatterns+=[
    path(r'hardware_emulation',views.hardwareEmulation,name="hardwareEmulation")
]

urlpatterns+=[
    path(r'ns3_simulation',views.uanEmulationForNs3,name="ns3Simulation")
]
#讨论区，
urlpatterns+=[
    path(r'comment',views.commentArea,name="comment")
]
#我的讨论区
urlpatterns+=[
    path(r'my_comment',views.getMyComment,name="my_comment")
]
#删除我的一条讨论
urlpatterns+=[
    path(r'my_comment/<int:pf>',views.deleteMyComment,name="delete_mycomment")
]
#点赞一条评论
urlpatterns+=[
    path(r'comment/<int:pf>',views.goodComment,name="GoodComment")
]
#test1
# 查看在线节点
urlpatterns+=[
    path(r'viewOnlineNodes', views.viewOnlineNodes, name = "viewOnline"),
    path(r'viewOneNode/<int:nodeId>', views.viewOneNode, name = "viewOneNode"),
    path(r'viewUanEmulation', views.uanEmulation, name = "viewUanEmulation"),
    path(r'uanHistory', views.UanEmulationListView.as_view(), name = "uanHistory"),
    path(r'uanHistory/<int:pf>/delete', views.deleteUanEmulation, name = "uan_delete"),
    path(r'uanHistory/<int:pf>/downloadSource', views.downloadUanEmulationSource, name = "uanSourceDownload"),
    path(r'uanHistory/<int:pf>/downloadResult', views.downloadUanEmulationResult, name = 'uanResultDownload')
]

# ship
urlpatterns+=[
    # path(r'viewpoision', views.viewpoision, name = "viewpoision"),
    path(r'poirefresh', views.poirefresh, name = "datarefresh"),
    path(r'viewonlinenodemsg/msgrefresh', views.msgarefresh, name = "msgdatarefresh"),
    path(r'viewonlinenodemsg/sendcommand', views.sendcommand, name = "sendcommand"),
    path(r'viewonlinenodemsg/sendarea', views.sendarea, name = "sendarea"),
    path(r'viewonlinenodemsg/sendpointroute', views.sendpointroute, name = "sendpointroute"),
    path(r'viewonlinenodemsg/sendlineroute', views.sendlineroute, name = "sendlineroute"),
    path(r'viewonlinenodemsg/<int:nodeId>', views.onlinenodemsg, name = "onlinenodemsg"),
]

#nodetest
urlpatterns+=[
    path(r'nodetest', views.nodetest, name = "nodetest"),
    path(r'shiphistory', views.shiplistview.as_view(), name="shiphistory"),
    path(r'shipHistory/<int:pf>/downloadSource', views.downloadshipEmulationSource, name = "shipSourceDownload"),
    path(r'shipHistory/<int:pf>/downloadResult', views.downloadshipEmulationResult, name = "shipResultDownload"),
    path(r'shipHistory/<int:pf>/delete', views.deleteshipEmulation, name = "ship_delete"),


]

water/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^nodeapp/',include('nodeapp.urls')),
    #url(r'^$',RedirectView.as_view(url='/nodeapp/',permanent=True)),
		
]
from django.views import static
urlpatterns+= [
    url(r'^static/(?P<path>.*)$', static.serve,
      {'document_root': settings.STATIC_ROOT}, name='static'),
]

nodeapp/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.urls import reverse
from django.urls import reverse
from django.contrib.auth.models import User  #从django中的模型导入用户模型。
#表明每个用户做仿真的时候所设置了参数，一个用户可能对应多个参数设置

#仿真参数
class SimulationParament(models.Model):
    #用户
    SimulationUser = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True) 

    #仿真参数
    TestName = models.CharField(max_length=100,help_text="the name of test")    #实验名称

    #7个不同的仿真参数
    #NumNode = models.IntegerField(help_text="仿真节点数量，The number of Nodes")  #仿真节点数量   
    RecvNodeMac = models.CharField(max_length=18,default="",help_text="接收消息节点的物理地址")
    SendNodeMac = models.CharField(max_length=18,default="",help_text="发送消息的节点物理地址")

    Modulation = models.CharField(max_length=10,help_text="调制方式，Modulation,QPSK,MFSK") #调制方式，QPSK,MFSK
    MACPtorocols = models.CharField(max_length=50,help_text="MAC层协议,for example,aloha protocol") # MAC层协议
    Route = models.CharField(max_length=50,help_text="路由协议,route protocols")     #路由协议   
    Transport = models.CharField(max_length=50,help_text="传输层协议,for instance,UDP")  #传输层协议
    Application = models.CharField(max_length=50,default="CBR",help_text="应用层协议,for instance,CBR") #应用层协议
    Simulation = models.CharField(max_length=50,help_text="硬件仿真还是软件仿真,simulation or emulation")  #硬件仿真还是软件仿真
    
    #仿真起始时间
    RunningTime = models.DateTimeField("仿真开始时间",default=timezone.now)

    #仿真结果
    PacketLoss = models.IntegerField(help_text="PacketLoss，丢包率",default=-1)
    Delay = models.IntegerField(help_text="delay ,延时",default=-1)
    AverageThroughput = models.IntegerField(help_text="AverageThroughput,平均吞吐量",default=-1)#怎么改为浮点型数，这是一个小问题
    class Meta:  
        ordering = ['-RunningTime']  #按照运行起点时间排序
        #permissions=((""),)

    def __str__(self):
        return self.TestName
    def get_absolute_url(self):
        return reverse("simulationparament_detail",args=[str(self.id)])
    


#项目负责人名单，即管理者,与用户无关
class Management(models.Model): #因为“adminstrator”可能存在与系统当中，故避开此词
    name=models.CharField(max_length=20,help_text="the name of administrator") #管理者名字
    job = models.CharField(max_length=50,help_text="job") #工作岗位
    call = models.CharField(max_length=11,help_text="the phone number") #电话
    email = models.EmailField(max_length=50,help_text="the email of manager") #email
    office_address=models.CharField(max_length=100,help_text="office address") #办公地址

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("management_detail",args=[str(self.id)])

"""
数据表构造思路图
|---------------------------------------------------------------|
|           节点MAC属性         |                  |             |
|           节点网络属性         |                  |             |
|           节点地理属性         |                  |             |
|------------------------------|                  |             |
| 节点PH值属性 |                 |   水声节点属性     |             |
| 节点温度属性 |  节点信息采集属性  |                  |             |
| 节点压强属性 |                 |                  |   时刻节点   |
|------------------------------|                  |             |
|        节点逻辑属性（节点ID）   |                  |              |
|-------------------------------------------------|             |
|                     时刻                         |             |
|---------------------------------------------------------------|

仿真数据表构造图
|--------------------|
| 发送节点（时刻节点）  |
| 接收节点（时刻节点）  |
| 发送文件            |
| 接收文件            |
|--------------------|

仿真结果计算数据表构造图
|
"""

class Net_Attribute(models.Model): #网络层属性
    Node_IPv4 = models.GenericIPAddressField(help_text = "Node IPv4 address")
    
    def __str__(self):
        return self.Node_IPv4
    
class MSG_PH_Attribute(models.Model): #采集信息属性_ph value
    Node_PH = models.DecimalField(max_digits=3,decimal_places=1,default = 7.0,help_text="PH value, such as 7.00，12.01")
    
    def __str__(self):
        return str(self.Node_PH)

class MSG_Temperature_Attribute(models.Model): # temperature
    Node_Temperature = models.DecimalField(max_digits=4,decimal_places=1,default = 20.0,help_text = "Temperature , such as 37.0 centidegree")

    def __str__(self):
        return str(self.Node_Temperature)

class MSG_Press_Attrubute(models.Model): # water pressure
    Node_Press = models.DecimalField(max_digits=6,decimal_places=2,default = 101.01,help_text = "water pressure, such as 101.01 KPa")
    def __str__(self):
        return str(self.Node_Press)

"""
原生节点(裸节点)，放置节点的时候，需要这三个信息：物理地址，地理位置以及逻辑序号
在实地使用的时候，一定会用逻辑序号来区分节点，而不会用MAC地址来区分节点，但对于这些原始节点来说，其内在的最大不同在于MAC地址，
"""
class Raw_Node(models.Model): #放置节点时，信息
    RawNode_ID = models.IntegerField(primary_key = True,help_text="节点逻辑序号,从1开始计数") #
    Geo_Address = models.CharField(max_length = 255, default = "", help_text = "node geography address")
    MAC_Address = models.CharField(max_length=18,default="",help_text="原始节点的物理地址") #可以认为在四五年内不会变更，因而是固定的
    
    def __str__(self):
        return str(self.RawNode_ID)

"""
时刻节点,以时间和原生节点为主键：表示某一时刻，节点的IP地址和收集到的信息
这里必须使用联合主键，因为IP地址，MSG既与时刻有关系，又与原生节点有关联
"""
from django.utils import timezone
class Time_Node(models.Model):
    Note_Time = models.DateTimeField(help_text="记录时间",auto_now_add=True)
    Note_Node = models.ForeignKey(Raw_Node,on_delete=models.SET_NULL,blank = True,null = True,help_text="原始节点")

    IP_Address = models.ForeignKey(Net_Attribute,on_delete = models.SET_NULL,null = True,blank = True,help_text="IP地址")

    Note_PH = models.ForeignKey(MSG_PH_Attribute,on_delete = models.SET_NULL,null = True,blank = True,help_text="PH value")
    Note_TP = models.ForeignKey(MSG_Temperature_Attribute,on_delete = models.SET_NULL,null = True,blank = True,help_text="temperature,(centidegree) ")
    Note_PS = models.ForeignKey(MSG_Press_Attrubute,on_delete = models.SET_NULL,null = True,blank = True,help_text="Pressure,(KPa)")

    class Meta:
        unique_together = ("Note_Time","Note_Node")
    
    def __str__(self):
        return str(self.Note_Time) + str(self.Note_Node)

    def get_absolute_url(self):
        return reverse("Time_Node_detail",args=[str(self.id)])

#仿真结果数据表
class Simultaion_Result(models.Model):
    Loss_Packet = models.DecimalField(max_digits=3,decimal_places=2,default = 0.00,help_text = "loss packet")
    Delay_Time = models.IntegerField(default=0,help_text="Millisecond")

    def __str__(self):
        return str(Loss_Packet)
#未完待续


"""
#硬件仿真数据表
本实验是一对一的实验，即一个发射节点，一个接收节点
"""

class Emulation_Test(models.Model):
    Test_Name = models.CharField(max_length = 100 , help_text = "test name") #测试用例名字
    Emul_Time = models.DateTimeField(help_text = "仿真时间" , auto_now=True)  #仿真开始时间

    #一次实验，选一个接收节点，一个发射节点。而每个节点都可能有多次实验
    Recv_Node = models.ForeignKey(Raw_Node, related_name="Recv",on_delete = models.SET_NULL,null = True,help_text="Recv Node") #
    Send_Node = models.ForeignKey(Raw_Node, related_name="Send",on_delete = models.SET_NULL,null = True,help_text="Send Node")

    Recv_File = models.FileField(help_text="Receive File",blank = True)
    Send_File = models.FileField(help_text="Send File",blank = True)

    def __str__(self):
        return ("%s,%s" % (self.Test_Name,str(Emul_Time)))

    def get_absolute_url(self):
        return reverse("Emulation_Test_detail",args=[str(self.id)])


"""=============================================================
留言板，数据库设计
================================================================"""

class Message_Board(models.Model):
    MSG_Time = models.DateTimeField(auto_now=True,help_text="留言时间")
    #留言者
    Commenter = models.ForeignKey(User,related_name="Commenter",on_delete=models.SET_NULL,null=True,blank=True,help_text="only registered user can user ite")
    LeavingMSG = models.CharField(max_length=250,help_text="leaving message")
    #评论者

"""
 =============================================================
class Topic(models.Model)
用户发起一个话题，
================================================================"""   
class Topic(models.Model):
    Title = models.CharField(max_length=30,help_text="the title of this topic") #话题主题
    #话题发起人
    Spoke_Man = models.ForeignKey(User,related_name="Spoke_Man",on_delete=models.SET_NULL,null=True,blank=True,help_text="only registered user can user ite")
    Content = models.TextField(max_length=250,help_text="talk about") #说了什么事情
    Spoke_Time = models.DateTimeField(auto_now=True,help_text="话题发起时间")
    #评论者
    Reviewer_MSG = models.ManyToManyField(Message_Board,default = None,help_text="留言")
    #点赞
    Good = models.IntegerField(default=0,help_text="点赞数量")
    def __str__(self):
        return self.Title
    
    def get_absolute_url(self):
        return reverse("comment_detail",args=[str(self.id)])


"""
pl
"""
class UanEmulation(models.Model): 
    # 1. taskID
    taskID = models.CharField(max_length=48, help_text = "the id of emulation task")
    
    # 2. user
    emuUser = models.ForeignKey(
        User, 
        related_name = "emuUser", 
        on_delete = models.SET_NULL, 
        null = True,
        blank = True, 
        help_text = "registered user can use"
    )
    
    # 3. the source file
    srcFilePath = models.CharField(max_length = 255, help_text = "the srcFilePath")
    
    # 4. the result of emulated files
    emuFilesPath = models.CharField(max_length = 255, help_text = "the emulated files ")
    
    # 5. emulated time
    emuTime = models.DateTimeField(auto_now = True, help_text = "the emulated time")
    
    # 6. src node
    srcNodeID = models.ForeignKey(
        Raw_Node, 
        related_name = "srcNodeId", 
        on_delete = models.DO_NOTHING,
        help_text = ""
    ) 

    def __str__(self):
        return self.taskID

    def get_absolute_url(self):
        return reverse("uanEmulatedDetail", args = [str(self.id)])

# 无人船信息
class Ship_msg(models.Model):
    Ship_ID = models.IntegerField(primary_key=True,default = 0, help_text="节点逻辑序号,从1开始计数")  #

nodeapp/templates/Emulation/Node_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h3 style="text-align:center">水声节点属性</h3> 
<p>第{{nodeID}}号节点</p>
<p>地理位置:{{geoAddr}}</p>
<p>水温:{{temperature}} &#8451;</p>
<p>水压:{{pressure}}&emsp;kPa</p>
<p>PH:{{ph}}</p>


{% endblock content %} 

nodeapp/templates/Emulation/RealTimeMonitor.html
{% extends "base_generic.html" %}

{% block content %}
<p> </p>
<h3>&emsp;实时监测所有在线节点</h3>
 
<form action="" method="POST" name="AllNodes" class="uanMonitor">
    {% csrf_token %}
    <table>
        <tr>
            <th>节点序号</th>
            <th>选择</th>
        
        </tr>
        {% for node in nodeIDs %}
        <tr>
            <td><a href="/nodeapp/viewOneNode/{{node}}">{{node}}</a></td>
            <td><input type="checkbox" name = "nodeID" value="{{node}}"></td>
        </tr>
       {% endfor %}
    </table>
    <label>65535为web server的NodeID</label>
    <hr>
    <label>
        <input type="submit" name = "getNodes" id = "realsubmit">
    </label>
</form>



{% endblock content %} 

nodeapp/templates/Emulation/hardware_emulation.html
<!--
    硬件仿真界面文档
    本文档主要展示，选择两个节点进行仿真，并能实现在发射节点放入要发送的文档，或者图片，在接收节点收到该文档或者图片
-->

{% extends "base_generic.html" %}
{% block title %}
    <title>硬件仿真</title>
{% endblock %}

{% block content %}
<p>&nbsp;</p>
<h1 style="text-align:center">Hardware Emulation</h1>

<hr>
<form action="{% url 'hardwareEmulation' %}" method="post" name="form_update">
    {% csrf_token %}

    <h3>&emsp;1. 根据下面内容查看节点? <input type="submit" name = "SeeNode" value="查看节点"></h3>
    <p>
        <label>
        <input type = "radio" name = "See" value = "All Nodes">查看所有节点
    </label>
    <label>
        <input type = "radio" name = "See" value = "Online Nodes">查看所有在线节点
    </label>
    <label>
        <input type = "radio" name = "See" value = "Online Nodes and Sleep Nodes">查看所有在线节点和睡眠节点
    </label>
    <label>
        <input type = "radio" name = "See" value = "Poweroff Nodes">在数据库中查看已经关机的节点（暂未开通）
    </label>

    </p>
    
    <!---->
</form>

<hr>
<h3>&emsp;2.仿真信息</h3>
<form action="{% url 'hardwareEmulation' %}" method="POST" name="start_emulation" enctype="multipart/form-data"> <!--不对表单数据编码-->
    {% csrf_token %}
    <div>
        <p>
        <label>
            实验名称:
            <input type = "text" name="Test_Name">
        </label>
        </p>
    </div>
    <div id = "send_msg">
        <h2 style="text-align:center;">1.发射部分</h2>
        <p>1.请选择发射节点：
                {% for i in All_Nodes %}
                {{i}}
            {% endfor %}
        </p>
        <p>2.请上传发射节点要发送的文件： </p>
        <p>&emsp;
            <input type="file" name = "SendFile">
        </p>
        <p style="color:red">
            {{ UpLoadFile_Result }}
        </p>
    </div>
    
    <div id = "recv_msg">
        <h2 style="text-align:center">2. 接收部分</h2>
        <p>1.请选择接收节点：</p>
        <p>
            
            2.接收文件
        </p>
    </div>
   

    <div id="simulation_bottom">
        &emsp;
    </div>
    <div id = "submit_div" >&emsp;
        <input type = "reset" name = "Reset_Emulation" value = "重新设置">
        {% if user.is_authenticated %}
            <input type="submit" name="Start_Emulation" value="开始仿真" type="left:50%;">
        {% else %}
            <input type="button" name = "No_Access_Submit" value="开始仿真" onclick="no_access_submit()">
        {% endif %}
    </div>
    <hr>
    <div id="simulation_bottom">
        &emsp;
    </div>
    <hr>
</form>
{% endblock content %} 

nodeapp/templates/Emulation/uan_emulation.html
{% extends "base_generic.html" %}

{% block content %}
<div>
    <br>
    <h3>&emsp;硬件仿真</h3>
</div>
<div id = "uanEmulation">
<form action="{% url 'viewUanEmulation' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        请输入仿真原始数据文件:
        <input type="file" name = "emuFile">
        <br>
        请输入仿真运行脚本：
        <input type="file" name = "EmuScript">	
    </div>
    <hr>
    <div>
        请选择发射节点：
        <select name = "sendNodeId">
            {% for node in onlineNodes %}
            <option value = "{{node}}">第{{node}}节点</option>
            {% endfor %}
        </select>
    </div>
    <br>
    <div>
        请选择接收节点:
        <select name = "recvNodeIds" multiple = "multiple">
            {% for node in onlineNodes %}
            <option value = "{{node}}">第{{node}}节点</option>
            {% endfor %} 
        </select>
    </div>
    <div>
        <input type="submit" value = "开始仿真">
    </div> 
</form>

</div>

{% endblock content %}

nodeapp/templates/Emulation/uan_history.html
{% extends "base_generic.html" %}

{% block content %}

{% if uanemulation_list %}
<div class = "uanMonitor">
    <br>
    <h2>我的历史记录</h2>
</div>
<table class = "uanMonitor">
    <tr>
      <th>&emsp;&emsp;emuTime&emsp;&emsp;</th>
      <th>&emsp;&emsp;source file&emsp;&emsp;</th>
      <th>&emsp;&emsp;status&emsp;&emsp;</th>
      <th>&emsp;&emsp;delete&emsp;&emsp;</th>
    </tr><o></o>
  {% for aEntry in uanemulation_list %}
    <tr>
        <td>{{aEntry.emuTime}}</td>
        <td>
		<a href="{% url 'uanSourceDownload' pf=aEntry.id %}">
                下载</td>
            </a>
	{% if aEntry.emuFilesPath is None  %}
          <td>运行中</td>
	{% else %}
	<td><a href = "{% url 'uanResultDownload' pf=aEntry.id %}">下载</a></td>
	{% endif %}
	<td>
		<a href = "{% url 'uan_delete' pf=aEntry.id %}">delete</a>
	</td>
    </tr>

  {% endfor %}

</table>

{% endif %}

{% endblock content %}

nodeapp/templates/Emulation/uan_ns3_simulation.html
{% extends "base_generic.html" %}

{% block content %}
<div id = "uanEmulation">
<form action="{% url 'viewUanEmulation' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
	    <h2>ns-3仿真</h2>
	<h3><input type="radio" name="plan" value="plan1">1:ns-3初级软件仿真</h3>
	<p>A1.请输入仿真通信源文件:<input type="file" name = "emuFile"></p>
	
	<p>B1.请设置仿真脚本参数:</p>
	<p>&emsp;1, 能量：
	    <input type = "number" name = "energy" >
	(J, 焦耳)
	<br>
	&emsp;&emsp;&emsp;2, 噪音模型：高斯白噪声（ns3::AcousticModemEnergyModelHelper）<br>
	&emsp;&emsp;&emsp;3, 信道模型：ns3::UanChannel<br>
	&emsp;&emsp;&emsp;4, 发射节点位置：(x, y, z)=
	    <input type = "number" name = "send_x" >
	    <input type = "number" name = "send_y" >
	    <input type = "number" name = "send_z" >
	<br>

	&emsp;&emsp;&emsp;5, 接收节点位置：(x, y, z)=
	    <input type = "number" name = "recv_x" >
	    <input type = "number" name = "recv_y" >
	    <input type = "number" name = "recv_z" >
	</p>
        &emsp;&emsp;注：仿真源文件为通信原始数据，节点位置模型：固定,节点数&#60;254, MAC层，物理层为ns-3内置模块
    </div>

    <div>
	<h3><input type="radio" name="plan" value="plan2">2:ns-3中级软件仿真</h3>
	<p>A2.请输入仿真通信源文件:<input type="file" name = "emuFile2"> </p>
	<p>B2.请输入仿真脚本:<input type = "file" name = "EmuScript2"> </p>
        &emsp;&emsp;注：仿真通信源文件为通信原始数据，仿真脚本为仿真所设置的物理层，MAC层脚本参数	
    </div>
    <div>
	<h3><input type="radio" name="plan" value="plan3">3:ns-3高级软、硬件仿真</h3>
	<p><a href="{% url 'terminalSelector' %}">原始ns-3软件包</a></p>
	&emsp;&emsp;注：可以自定义物理层和MAC层协议和模块，需自行设计运行程序
    <div>
        <input type="submit" value = "开始仿真">
    </div> 
</form>

</div>

{% endblock content %}